name: Distribute Release

on:
  push:
    tags:
      - 'v*'

jobs:
  distribute:
    name: Distribute to firebase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Fetch distribution file from secrets
        id: fetch_credential_file
        uses: timheuer/base64-to-file@v1
        with:
            encodedString: ${{ secrets.FIREBASE_DISTRIBUTION }}
            fileName: 'firebase_distribution.json'

      - name: Fetch play store credentials from secrets
        id: fetch_play_credentials
        uses: timheuer/base64-to-file@v1
        with:
          encodedString: ${{ secrets.PLAY_CREDENTIALS }}
          fileName: 'play_store_credentials.json'

      - name: Decode Keystore
        id: fetch_keystore
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'keystore/putio_tv_keystore.jks'
          encodedString: ${{ secrets.KEYSTORE }}

      - name: Distribute to firebase
        id: distribure_firebase
        run: >-
          bash ./gradlew :app:bundleRelease :app:appDistributionUploadRelease --warning-mode all
          -Pfirebase_distribution=${{ steps.fetch_credential_file.outputs.filePath }}
          -Pplay_store_credentials=${{ steps.fetch_play_credentials.outputs.filePath }}
          -Pputio_client_id=${{ secrets.PUTIO_CLIENT_ID }}
          -Pputio_client_secret=${{ secrets.PUTIO_CLIENT_SECRET }}
          -Ptmdb_auth_token=${{ secrets.TMDB_AUTH_TOKEN }}
          -Pbuild_number=${{ github.run_number }}
          -Pkeystore_password=${{ secrets.KEYSTORE_PASSWORD }}
          -Pkeystore_key_alias=${{ secrets.KEYSTORE_KEY_ALIAS }}
          -Pkeystore_key_password=${{ secrets.KEYSTORE_KEY_PASSWORD }}
          -Pkeystore=${{ steps.fetch_keystore.outputs.filePath }}